version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/run-docker-compose"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/run-docker-compose/offlineimap-docker"
    schedule:
      interval: "daily"