#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

if [[ -z "${DISABLE_FILE_WATCH_ON_OFFLINEIMAP_CONF}" ]]; then
    DISABLE_FILE_WATCH_ON_OFFLINEIMAP_CONF="false"
fi

# starting inotify to watch /config/offlineimap.conf and restart offlineimap if changed.
if [ "$DISABLE_FILE_WATCH_ON_OFFLINEIMAP_CONF" == "false" ] ; then
    while inotifywait -e modify /config/offlineimap.conf; do
        cp /config/offlineimap.conf /offlineimap.conf
        lsiown abc:abc /offlineimap.conf
        chmod 600 /offlineimap.conf
        s6-svc -h /run/service/svc-offlineimap
        echo "offlineimap has been restarted"
    done
else
    echo "filewatch is disabled -> sleep infinity"
    sleep infinity
fi