#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit
set -o pipefail
set -o nounset
if [[ "${TRACE-0}" == "1" ]]; then set -o xtrace; fi

# make our folders
mkdir -p \
    /app \
    /config \
    /data

# copy default config if not present in /config
if [[ ! -e /config/offlineimap.conf ]]; then
    cp /defaults/offlineimap.conf /config
fi

# copy config from /config to root
cp /config/offlineimap.conf /offlineimap.conf

# permissions
# chown -R abc:abc \
#     /config \
#     /offlineimap.conf \
#     /app \
#     /data
chown -R abc:abc \
    /offlineimap.conf \
    /app \
    /data

# chmod u=rwx,g=,o= /config
chmod u=rwx,g=,o= /app
chmod u=rwx,g=,o= /app/*
chmod u+rw --recursive /data
# chmod u=rw,g=,o= \
#     /config/* \
#     /offlineimap.conf
chmod u=rw,g=,o= \
    /offlineimap.conf