---
name: Keep workflows alive

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keep-github-actions-alive:
    name: Cronjob based GitHub action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Keep your GitHub Actions alive automatically
        uses: Entepotenz/keep-github-actions-alive-min-dependencies@v1
